#! /bin/sh

flameshot &
sxhkd &
nm-applet &
/home/hexa/.config/polybar/launch.sh &
picom -r 20 --experimental-backends --backend glx --xrender-sync-fence --blur-background-fixed &
feh --bg-fill /home/hexa/Pictures/foxy4.png

bspc monitor -d  ﭮ  爵 ﳁ

bspc config border_width        0
bspc config window_gap          9

bspc config top_padding 25
bspc config left_padding 1
bspc config right_padding 1
bspc config bottom_padding 20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

#bspc rule -a Docky layer=above manage=on border=off focus=off locked=on
#bspc rule -a xfce4-notes floating=on
bspc rule -a kitty desktop=^1 follow=on
bspc rule -a spotify desktop=^3 follow=on
bspc rule -a discord-canary desktop=^2 follow=on
bspc rule -a brave desktop=^4 follow=on
#bspc rule -a deluge desktop=^7 follow=on
